version: "3.9"

services:
  honeypot:
    build: .
    # ports:
    #   - "8089:8088"   # uncomment if you also want direct access
    environment:
      - LLM_BACKEND=ollama
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3.2:3b
    volumes:
      - ./logs:/logs
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    depends_on:
      - honeypot
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.htpasswd:/etc/nginx/htpasswd:ro
    restart: unless-stopped
